### ISSUE TITLE
Parameters chosen to calculate speech rates of LibriSpeech dataset

### ISSUE THREAD

**Issue by beknazar** [acetylSv/rhythmic-flexible-vc-arch#1]
Hello,
I read the paper and impressed with results.

I wanted to replicate the results, however, when I started preprocessing the LibriSpeech data I encountered some difference with paper and my results.

So, I was wondering what kind of parameter values you have used to calculate speechrate of the dataset? Silence threshold (dB), min dip between peaks (dB) and min pause duration (s)...

Thanks in advance.

**Comment by acetylSv** [comment]
Hi, thanks for your interest in this work.
The parameter setting of Praat is as default I believed. I picked the 20 fastest and 20 slowest speakers from "train-clean-100" partition of LibriSpeech and their IDs are as follow:
Fast `458 103 6925 201 298 328 460 5561 8609 2989 426 5192 4406 5463 4160 2952 1116 4014 5339 5456`
Slow `7517 3374 322 7505 8238 7178 7447 2002 6181 6836 4640 669 445 412 6880 839 7780 1363 163 1447`
Hope this help solving your problem.
And also, I am currently working on a PyTorch implementation with some refinement and clean up of this work. I'll upload the codes when they are done.

**Comment by beknazar** [comment]
> Hi, thanks for your interest in this work.
> The parameter setting of Praat is as default I believed. I picked the 20 fastest and 20 slowest speakers from "train-clean-100" partition of LibriSpeech and their IDs are as follow:
> Fast `458 103 6925 201 298 328 460 5561 8609 2989 426 5192 4406 5463 4160 2952 1116 4014 5339 5456`
> Slow `7517 3374 322 7505 8238 7178 7447 2002 6181 6836 4640 669 445 412 6880 839 7780 1363 163 1447`
> Hope this help solving your problem.
> And also, I am currently working on a PyTorch implementation with some refinement and clean up of this work. I'll upload the codes when they are done.

Thanks, @acetylSv for the detailed answer.

PS. I can also contribute to the implementation part, if you need an extra hand, since currently in our lab we are experimenting with these projects often. Anyway, looking forward to the codes.
